django-model-main/django-model-main/alba/urls.py
from django.urls import path
from . import views


urlpatterns = [
path('', views.index, name='index'),
path('', views.index, name='index'),
path('albums/', views.AlbumListView.as_view(), name='albums'),
path('albums/<int:pk>/', views.AlbumDetailView.as_view(), name='album_detail'),
path('albums/zanr/<str:album_zanr>/', views.AlbumListView.as_view(), name='album-zanr'),
]

django-model-main/django-model-main/projekt/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('alba/', include('alba.urls')),
    path('', RedirectView.as_view(url='alba/')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django-model-main/django-model-main/alba/models.py
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator
def poster_path(instance, filename):
    return "alba/images/" + str(instance.nazev) + "/poster/" + filename

class Vydavatelstvi(models.Model):
    nazev = models.CharField(max_length=50, unique=True, verbose_name='Název vydavatelství', help_text='Zadejte název vydavatelství')

    class Meta:
        ordering = ['nazev']

    def __str__(self):
        return self.nazev

class Certifikace(models.Model):
    oceneni = models.CharField (max_length=20, unique=True, verbose_name='Název ocenění', help_text='Zadejte název ocenění')

    class Meta:
        ordering = ['oceneni']

    def __str__(self):
        return self.oceneni


class Zanr(models.Model):
    zanr = models.CharField (max_length=20, unique=True, verbose_name='Název žánru', help_text='Zadejte název žánru')

    class Meta:
        ordering = ['zanr']

    def __str__(self):
        return self.zanr


class Interpret(models.Model):
    POHLAVI = [
        ('Muž','Muž'),
        ('Žena', 'Žena')
    ]

    jmeno = models.CharField (max_length=50, verbose_name='Jméno umělce', help_text='Zadejte jméno umělce')
    prijmeni = models.CharField(max_length=50, verbose_name='Příjmení umělce', help_text='Zadejte příjmení umělce')
    narodnost = models.CharField(max_length=50, verbose_name='Národnost umělce', help_text='Zadejte národnost umělce')
    pohlavi = models.CharField(max_length=5, choices=POHLAVI, verbose_name='Pohlaví umělce', help_text='Vyberte pohlaví umělce')
    datumN = models.DateField(verbose_name='Datum narození', help_text='Vyberte datum narození')
    datumU = models.DateField(blank=True, null=True, verbose_name='Datum umrtí', help_text='Vyberte datum umrtí')

    class Meta:
        ordering = ['prijmeni']

    def __str__(self):
        return f'{self.jmeno} {self.prijmeni}'


class Album(models.Model):
    FORM = [
        ('LP', 'LP'),
        ('EP', 'EP'),
        ('Single', 'Single')
    ]
    nazev = models.CharField(max_length=100, verbose_name='Název alba', help_text='Zvolte název alba')
    hodnoceni = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(10)], verbose_name='Hodnocení', help_text='Ohodnoťte album')
    forma = models.CharField(max_length=10, choices=FORM, verbose_name='Forma alba', help_text='Zvolte formu alba')
    datumV = models.DateField(verbose_name='Datum vydání', help_text='Zvolte datum vydání')
    certifikace = models.ForeignKey(Certifikace, on_delete=models.CASCADE)
    vydavatelstvi = models.ForeignKey(Vydavatelstvi, on_delete=models.CASCADE)
    zanr = models.ManyToManyField(Zanr, help_text='Zvolte žánry')
    interpret = models.ManyToManyField(Interpret, help_text='Zvolte interpreta')
    image = models.ImageField(upload_to=poster_path, blank=True, null=True, verbose_name="Náhledový obrázek")
    runtime = models.IntegerField(null=True, verbose_name="Délka alba")

    class META:
        ordering = ['nazev']

    def __str__(self):
        return self.nazev


class Pisen(models.Model):
    nazev = models.CharField(max_length=100, verbose_name='Název skladby', help_text='Zadejte název skladby')
    delka = models.TimeField(verbose_name='Délka stopy', help_text='Zadejte délku stopy')
    poradi = models.IntegerField(verbose_name='Pořadí stopy', help_text='Zadejte pořadí stopy')
    album = models.ForeignKey(Album, on_delete=models.CASCADE)

    class META:
        ordering = ['nazev']

    def __str__(self):
        return self.nazev

django-model-main/django-model-main/alba/views.py
from django.shortcuts import render
from alba.models import Album, Zanr
from django.views.generic import ListView, DetailView

class AlbumListView(ListView):
 model = Album
 context_object_name = 'albums_list'
 # Umístění a název šablony
 template_name = 'list.html'

 def get_queryset(self):
  if 'album_zanr' in self.kwargs:
   return Album.objects.filter(zanr__zanr=self.kwargs['album_zanr']).all()
  else:
   return Album.objects.all()

 def get_context_data(self, **kwargs):
  context = super().get_context_data(**kwargs)
  context['num_albums'] = len(self.get_queryset())

  if 'album_zanr' in self.kwargs:
   context['view_title'] = f"Žánr: {self.kwargs['album_zanr']}"
   context['view_head'] = f"Žánr alba: {self.kwargs['album_zanr']}"
  else:
   context['view_title'] = 'Alba'
   context['view_head'] = 'Přehled Alb'
  return context



class AlbumDetailView(DetailView):
  # Nastavení požadovaného modelu
 model = Album

 context_object_name = 'album_detail'
 # Umístění a název šablony
 template_name = 'detail.html'


def index(request):

 context = {
  'albumss': Album.objects.order_by('-datumV')[:3],
  'deset': Album.objects.order_by('-hodnoceni').all()[:10],
  'zanrs': Zanr.objects.order_by('zanr').all(),
  'num_albums': Album.objects.all().count(),
  'albums': Album.objects.order_by('-hodnoceni')[:6],
 }

 """ Pomocí metody render vyrendrujeme šablonu index.html a předáme ji hodnoty v proměnné context k zobrazení """
 return render(request, 'index.html', context=context)

django-model-main/django-model-main/alba/templates/base.html
<!DOCTYPE html>
<html lang="cs">
<head>
<link rel="icon" type="image/x-icon" href="../../static/img/morb.jpg">
 <title>{% block title %}Knihovna Alb{% endblock %}</title>
 <meta charset="utf-8">
 <meta name="viewport" content="width=device-width, initial-scale=1">
 <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">

 {% load static %}
{% block css %}
 {% endblock %}
 <link rel="stylesheet" href="{% static '../static/css/style.css' %}">
</head>
<body>
 {% block header %}
    {% include "page/header.html" %}
 {% endblock %}

 {% block navbar %}
    {% include "page/navbar.html" %}
 {% endblock %}

 <main>
    <div class="container-fluid">
        {% block content %}{% endblock %}
    </div>
 </main>

 {% block footer %}
    {% include "page/footer.html" %}
 {% endblock %}


 <script
src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>

 <script
src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>

 <script
src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>

 {% block scripts %}{% endblock %}
</body>
</html>

django-model-main/django-model-main/alba/templates/blocks/deset.html
<ol class="list-group">
    {% for album in deset %}
        <li class="list-group-item list-group-item-danger d-flex justify-content-between align-items-center">
            <a class="text-dark" href="{% url 'album_detail' album.id %}">{{ album.nazev }}</a>
            <span class="badge badge-pill badge-danger">{{ album.hodnoceni }}</span>
        </li>
    {% endfor %}
</ol>

django-model-main/django-model-main/alba/templates/blocks/new_albums.html
{% load mathfilters %}
<div>
    {% for album in albumss %}
        <div class="row mb-4 border-bottom">
            <div class="col-md-2">
                {% if album.image %}
                    <img class="card-img-top" src="{{ album.image.url }}" alt="{{ album.nazev }}">
                {% endif %}
                </a>
            </div>
            <div class="col-md-8">
                <h4><a href="{% url 'album_detail' album.pk %}">{{ album.nazev|upper }}</a></h4>
                <p class="card-text"><strong>
                    {% for interpret in album.interpret.all %}
                        {{ interpret.jmeno }} {{ interpret.prijmeni }}
                    {% endfor %}
                </strong></p>
                <hr>
                <p class="text-center display-5 mb-3 font-italic"><u>Seznam stop</u></p>
             {% for pisen in album.pisen_set.all %}
                    <p>{{ pisen.poradi }}. {{ pisen.nazev }} | {{ pisen.delka|date:"i:s" }} |</p>
                {% endfor %}
                <hr>
                <p>Stopáž: {{ album.runtime }} min., datum uvedení: {{ album.datumV|date:'d.m.Y' }}</p>
                <p>Žánry: {% for zanr in album.zanr.all %}
                    <a href="{% url 'album-zanr' zanr.zanr %}" class="btn btn-info">  {{ zanr }}  </a>
                {% endfor %}</p>
            </div>
            <div class="col-md-2">
                <span class="display-4">{{ album.hodnoceni }}</span>
                <div class="progress">
                    <div class="progress-bar bg-info"
                         style="width:{{ album.hodnoceni|mul:'10'|floatformat }}%"></div>
                </div>
            </div>
        </div>
    {% endfor %}
</div>

django-model-main/django-model-main/alba/templates/blocks/zanr_list.html
<ul class="list-group">
    {% for zanr in zanrs %}
        <li class="list-group-item list-group-item-info">
            <a class="text-dark" href="{% url 'album-zanr' zanr.zanr %}">{{ zanr }}</a>
            <span class="badge badge-dark">{{ zanr.album_set.all.count }}</span>
        </li>
    {% endfor %}
</ul>

django-model-main/django-model-main/alba/templates/detail.html
{% extends "base.html" %}
{% block title %}Detail alb{% endblock %}
{% block css %}
 <link href="https://cdnjs.cloudflare.com/ajax/libs/ekko-lightbox/5.3.0/ekkolightbox.css" rel="stylesheet">
{% endblock %}
{% block content %}
<div class="row mb-3">
 <div class="col-sm-12 bg-warning">
 <h2 class="display-4 text-center">Podrobné informace</h2>
 </div>
</div>
<div class="row mt-5 mb-3">
 <div class="col-lg-6 mb-3">

      <h2 class="display-4 mb-3"><strong>{{ album_detail.nazev }}</strong></h2>
    <hr>

    {% for interpret in album_detail.interpret.all %}
        <h3 class="display-5 mb-4">{{ interpret.jmeno }} {{ interpret.prijmeni }}{% endfor %}
        </h3>

 <div class="bg-secondary text-light p-2 mb-3">Datum vydání: {{ album_detail.datumV }} | Hodnocení: {{ album_detail.hodnoceni }} z 10
     <!-- Řešení zobrazení hodnocení filmu ve formě hvězdiček -->
    | {% with ''|center:album_detail.hodnoceni as range %}
 {% for _ in range %}★{% endfor %} |
 {% endwith %}
 <p></p>
      <p class = "bg-secondary text-light mb-1">Vydavatelství: {{ album_detail.vydavatelstvi }} | Forma: {{ album_detail.forma }} | Certifikace: {{ album_detail.certifikace }} |</p>
 </div>
 <div class="row">
 <div class="col-md-12">
      <hr>
    <h3 class="text-center display-5 mb-3 font-italic"><u>Seznam stop</u></h3>
     <hr>
     {% for pisen in album_detail.pisen_set.all %}
         <p>{{ pisen.poradi }}. {{ pisen.nazev }} | {{ pisen.delka|date:"i:s" }} |</p>
     {% endfor %}
    <hr>
     <p><strong>Stopáž: {{ album_detail.runtime }} min.</strong></p>
 </div>
 </div>
 </div>
 <div class="col-lg-6 bg-light p-3">
 <h3 class="border-bottom pb-3 text-secondary text-center textuppercase">Vizuální reprezentace alba</h3>
 <div class="row">
 {% if album_detail.image %}
 <a class="rounded mx-auto d-block" href="{{ album_detail.image.url }}">
 <img src="{{ album_detail.image.url }}" class="img-fluid"
alt="Vizuální reprezentace alba">
 </a>
 {% endif %}
 {% for image in album_detail.attachment_set.all %}
 <div class="col-lg-6 col-xl-4">
 <a href="{{ image.file.url }}" data-toggle="lightbox" datagallery="gallery">
 <img src="{{ image.file.url }}" class="img-fluid img-thumbnail" alt="{{ image.title }}">
 </div>
 {% endfor %}
 </div>
 </div>
</div>
{% endblock %}
{% block scripts %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/ekko-lightbox/5.3.0/ekkolightbox.min.js"></script>
<script>
 $(document).on("click", '[data-toggle="lightbox"]', function(event) {
 event.preventDefault();
 $(this).ekkoLightbox();
 });
</script>
{% endblock %}


django-model-main/django-model-main/alba/templates/index.html
{% extends "base.html" %}
{% block content %}
    <div class="row mb-3">
        <div class="col-sm-12 bg-warning">
            <h2 class="display-4 text-center">Úvodní stránka</h2>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6">
            <h2 class="text-center bg-success text-light p-2">Nové alba</h2>
            {% include "blocks/new_albums.html" %}
        </div>
        <div class="col-md-3">
            <h2 class="text-center bg-danger text-light p-2">Top deset alb</h2>
            {% include "blocks/deset.html" %}
        </div>
        <div class="col-md-3">
            <h2 class="text-center bg-info text-light p-2">Žánry alb</h2>
            {% include "blocks/zanr_list.html" %}
        </div>
    </div>
    <div class="row">
    </div>
    <div class="row">
        <div class="col-sm-12">
            <strong>Celkový počet alb:</strong> {{ num_albums }}
        </div>
    </div>
{% endblock %}


django-model-main/django-model-main/alba/templates/list.html
{% extends "base.html" %}

{% block title %}{{ view_title }}{% endblock %}
<!-- Obsahový blok stránky -->
{% block content %}
<div class="row mb-3">
 <div class="col-sm-12 bg-warning">
 <h2 class="display-4 text-center">{{ view_head }}</h2>
 </div>
</div>

<div class="row">

 {% for album in albums_list %}
 <div class="col-sm-6 col-md-4 col-lg-4 col-xl-2">
 <div class="card">
 {% if album.image %}
 <img class="card-img-top" src="{{ album.image.url }}" alt="{{ album.nazev }}">
</div>
 {% endif %}
     <div class="card-body">
 <h4 class="card-title"><a href="{% url 'album_detail' album.pk %}">{{ album.nazev }}</a></h4>
 <p class="card-text">{% for zanr in album.zanr.all %}<a href="{% url 'album-zanr' zanr.zanr %}" class="btn btnlight">| {{ zanr }} |</a> {% endfor %}</p>
 <a href="{% url 'album_detail' album.pk %}" class="btn btn-primary">Podrobnosti</a>
 </div>
 </div>
 {% endfor %}
</div>
{% endblock %}



django-model-main/django-model-main/alba/templates/page/footer.html
{% load static %}
<footer class="container-fluid text-center">
 <hr>
 <p>&copy; Copyright Ondřej Repko - 2022</p>
</footer>

django-model-main/django-model-main/alba/templates/page/header.html
<header class="jumbotron-fluid p-5 text-center bg-dark">
    <h1 class="text-white text-uppercase display-3">Malá hudební databáze</h1>
</header>

django-model-main/django-model-main/alba/templates/page/navbar.html
<nav class="navbar navbar-expand-md bg-dark navbar-dark">
    <a class="navbar-brand text-warning" href="#">MHD</a>

    <button class="navbar-toggler" type="button" data-toggle="collapse" datatarget="#collapsibleNavbar">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="collapsibleNavbar">
        <ul class="navbar-nav">
            <li class="nav-item">
                <!-- Odkaz na úvodní stránku webu -->
                <a class="nav-link active" href="{% url 'index' %}">Úvodní stránka</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'albums' %}">Alba</a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" id="navbardrop" data-toggle="dropdown">Žánry</a>
                <div class="dropdown-menu" aria-labelledby="navbardrop">
                    {% for zanr in zanrs %}
                        <a class="dropdown-item" href="{% url 'album-zanr' zanr.zanr %}">{{ zanr }}</a>
                    {% endfor %}
                </div>
            </li>
        </ul>
    </div>
</nav>